spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/ISTAD/Expert/part II/self practice/configuration-management/yelp-config/{application}
